extends:
  - stylelint-config-standard
  - stylelint-config-property-sort-order-smacss

plugins:
  - stylelint-scss

rules:
  # Disallow "@extend" in scss.
  # http://csswizardry.com/2016/02/mixins-better-for-performance/
  # http://vanseodesign.com/css/sass-mixin-or-extend/
  # Besides performance, @extend actually *changes* the selector precedence by creating a compound
  # selector, which can lead to ambiguous results.
  at-rule-blacklist:
    - extend

  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - at-root
        - content
        - each
        - else
        - error
        - for
        - function
        - include
        - if
        - mixin
        - return
        - warn

  # The following prefix rules are enabled since we use autoprefixer
  at-rule-no-vendor-prefix: true
  media-feature-name-no-vendor-prefix: true
  property-no-vendor-prefix: true
  selector-no-vendor-prefix: true
  value-no-vendor-prefix: true

  color-hex-length: long

  #  comment-empty-line-before:
  #    - always
  #    -
  #      except:
  #        - first-nested
  #      ignore:
  #        - after-comment
  #        - stylelint-commands
  comment-empty-line-before: null

  declaration-colon-space-after: always-single-line

  declaration-no-important: true

  # Additional Airbnb config: https://gist.github.com/maechabin/f840d58a33f1d41c1d2d3852af08f7e3
  declaration-property-value-blacklist:
    /^border/: none

  # https://stackoverflow.com/a/34383157/467582
  function-url-quotes: always

  font-weight-notation: numeric

  font-family-name-quotes: always-where-recommended

  # Usually if you're nesting past 3 levels deep there's a problem
  max-nesting-depth: 3

  # https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md
  order/order:
    - - type: at-rule
        name: include
      - custom-properties
      - dollar-variables
      - declarations
      - at-rules
      - rules
      - type: at-rule
        name: include
        parameter: breakpoint
    - unspecified: ignore
      disableFix: true

  # Extremely useful for typos, and anything emergent can be ignored by this rule
  property-no-unknown:
    - true
  #    - ignoreProperties:
  # CSS Modules composition
  # https://github.com/css-modules/css-modules#composition
  #        - composes

  # https://www.w3.org/TR/selectors/#attribute-selectors
  # http://stackoverflow.com/q/3851091
  selector-attribute-quotes: always

  # Because we adhere to BEM we can limit the amount of necessary compound selectors. Most should
  # just be 1 level selector. However, modifiers can introduce an additional compound selector.
  # Furthermore, generic qualifying selectors (e.g. `[dir="rtl"]`) can introduce yet another level.
  selector-max-compound-selectors: 4

  # There is no reason that a specific ID would be needed for UI components
  selector-max-id: 0

  # For specificity: disallow IDs (0). Allow for complex combinations of classes, pseudo-classes,
  # attribute modifiers based on selector-max-compound-selectors, plus an addition for
  # pseudo-classes (4). Allow for pseudo-elements (1).
  selector-max-specificity: 0,4,1

  # In general, we should not be modifying elements within our components, since we can't
  # predict the use cases in which users would add a certain type of element into a component.
  selector-max-type:
    - 1
    - ignoreTypes:
        - /fieldset/

  # Styles for components should never need the universal selector.
  selector-max-universal: 0

  # Qualifying types are not needed when using a naming system like BEM
  selector-no-qualifying-type: true

  no-descending-specificity: null

  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        # CSS Modules :global scope
        # https://github.com/css-modules/css-modules#exceptions
        - global

  # Opinionated rule, reflecting how attribute strings are normally quoted within the DOM.
  string-quotes: double

  # Rules adaption for Sass
  #  scss/double-slash-comment-empty-line-before:
  #    - always
  #    -
  #      except:
  #        - first-nested
  #      ignore:
  #        - between-comments
  #        - stylelint-commands

  scss/double-slash-comment-inline:
    - never
    - ignore:
        - stylelint-commands

  scss/dollar-variable-colon-space-before: never
  scss/dollar-variable-colon-space-after: always-single-line
  scss/double-slash-comment-whitespace-inside:
    - always
    - severity: warning
  scss/selector-no-redundant-nesting-selector: true
